// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/thnkrn/go-fiber-crud-clean-arch/pkg/api"
	"github.com/thnkrn/go-fiber-crud-clean-arch/pkg/api/handler"
	"github.com/thnkrn/go-fiber-crud-clean-arch/pkg/api/middleware"
	"github.com/thnkrn/go-fiber-crud-clean-arch/pkg/config"
	"github.com/thnkrn/go-fiber-crud-clean-arch/pkg/db"
	"github.com/thnkrn/go-fiber-crud-clean-arch/pkg/repository"
	"github.com/thnkrn/go-fiber-crud-clean-arch/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.ServerHTTP, error) {
	errorHandler := middleware.NewErrorHandler()
	authentication := middleware.NewAuthentication()
	middlewares := &api.Middlewares{
		ErrorHandler:   errorHandler,
		Authentication: authentication,
	}
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	handlers := api.Handlers{
		UserHandler: userHandler,
	}
	serverHTTP := api.NewServerHTTP(middlewares, handlers, cfg)
	return serverHTTP, nil
}
